// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire gen -tags "wireinject"
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/angelokurtis/go-home-automations/pkg/app"
)

// Injectors from wire_inj.go:

func newAppRunner(ctx context.Context) (AppRunner, func(), error) {
	runner := app.NewRunner()
	return runner, func() {
	}, nil
}

// wire_inj.go:

type AppRunner interface {
	Run(ctx context.Context) error
}
