// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/angelokurtis/go-home-automations/internal/ha"
	"github.com/angelokurtis/go-home-automations/pkg/action"
	"github.com/angelokurtis/go-home-automations/pkg/app"
	"github.com/angelokurtis/go-home-automations/pkg/entity"
	"github.com/angelokurtis/go-home-automations/pkg/task"
)

import (
	_ "github.com/angelokurtis/go-home-automations/internal/logger"
)

// Injectors from wire_inj.go:

func NewRunner(ctx context.Context) (Runner, func(), error) {
	config, err := ha.LoadConfig()
	if err != nil {
		return nil, nil, err
	}
	gomeassistantApp, cleanup, err := ha.NewApp(ctx, config)
	if err != nil {
		return nil, nil, err
	}
	service := ha.NewService(gomeassistantApp)
	state := ha.NewState(gomeassistantApp)
	synchronizedSwitchesListeners := entity.NewSynchronizedSwitchesListeners(service, state)
	v := entityListeners(synchronizedSwitchesListeners)
	v2 := eventListeners()
	allSwitchesOff := action.NewAllSwitchesOff(service, state)
	v3 := dailyTasks(allSwitchesOff)
	eveningLightsOn := task.NewEveningLightsOn(service, state)
	v4 := sunsetTasks(eveningLightsOn)
	v5 := sunriseTasks()
	runner := app.NewRunner(gomeassistantApp, v, v2, v3, v4, v5, service, state)
	return runner, func() {
		cleanup()
	}, nil
}

// wire_inj.go:

type Runner interface {
	Run(ctx context.Context) error
}
