// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire gen -tags "wireinject"
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/angelokurtis/go-home-automations/pkg/app"
	"github.com/angelokurtis/go-home-automations/pkg/homeassistant"
)

// Injectors from wire_inj.go:

func newAppRunner(ctx context.Context) (AppRunner, func(), error) {
	config, err := homeassistant.NewConfigFromEnv()
	if err != nil {
		return nil, nil, err
	}
	gomeassistantApp, cleanup, err := homeassistant.NewApp(ctx, config)
	if err != nil {
		return nil, nil, err
	}
	service := homeassistant.NewServices(gomeassistantApp)
	light := homeassistant.NewLight(service)
	switchController := app.NewSwitchController(light)
	runner := app.NewRunner(gomeassistantApp, switchController)
	return runner, func() {
		cleanup()
	}, nil
}

// wire_inj.go:

type AppRunner interface {
	Run(ctx context.Context) error
}
