// Code generated by ifacemaker; DO NOT EDIT.

package app

// HomeAssistant defines methods for integrating with a Home Assistant instance
type HomeAssistant interface {
	Cleanup()
	RegisterSchedules(schedules ...DailySchedule)
	RegisterIntervals(intervals ...Interval)
	RegisterEntityListeners(etls ...EntityListener)
	RegisterEventListeners(evls ...EventListener)
	Start()
	GetService() *Service
	GetState() State
}
